python finetune.py \
    --data_root ./cus_dataset \
    --model_type vit_h \
    --checkpoint_path ./checkpoints/sam_vit_h_4b8939.pth \
    --freeze_image_encoder \
    --freeze_mask_decoder \
    --freeze_prompt_encoder \
    --train_VPT_decoder \
    --batch_size 5 \
    --image_size 1024 \
    --steps 1500000 \
    --learning_rate 1.e-4 \
    --weight_decay 0.01 \
    --metrics_interval 185