python finetune.py \
    --data_root ./dataset \
    --model_type vit_h \
    --checkpoint_path ./pre_trained/sam_vit_h_4b8939.pth \
    --freeze_mask_decoder \
    --freeze_prompt_encoder \
    --batch_size 4 \
    --image_size 1024 \
    --steps 1500000 \
    --learning_rate 1.e-5 \
    --weight_decay 0.01 \
    --metrics_interval 93